src/objects/maica_cc__Setting__c.object
<CustomObject>
    <fields>
        <fullName>Sync_Direction__c</fullName>
        <description>Setting API Name:Sync_Setting</description>
        <label>Sync Direction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Maica to Standard</fullName>
                </value>
                <value>
                    <fullName>Standard to Maica</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sync_Mode__c</fullName>
        <defaultValue>&apos;Triggered&apos;</defaultValue>
        <description>Setting API Name:Sync_Setting</description>
        <label>Sync Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Triggered</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>On Demand</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/maica_cc__Support_Item__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Support Items</relationshipLabel>
        <relationshipName>Support_Items</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Support_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Support Item</label>
        <referenceTo>maica_cc__Support_Item__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Support_Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Represents the Support Category that the Product belongs to.</description>
        <inlineHelpText>Represents the Support Category that the Product belongs to.</inlineHelpText>
        <label>Support Category</label>
        <referenceTo>maica_cc__Support_Category__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Day__c</fullName>
        <description>The specific day or delivery window when the Product is eligible for Service Delivery.</description>
        <inlineHelpText>The specific day or delivery window when the Product is eligible for Service Delivery.</inlineHelpText>
        <label>Service Day</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Weekday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Public Holiday</fullName>
                </value>
                <value>
                    <fullName>Anytime</fullName>
                    <default>true</default>
                    <label>Anytime</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Time__c</fullName>
        <description>The specific time of day when the Product is eligible for Service Delivery.</description>
        <inlineHelpText>The specific time of day when the Product is eligible for Service Delivery.</inlineHelpText>
        <label>Service Time</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daytime</fullName>
                </value>
                <value>
                    <fullName>Afternoon</fullName>
                </value>
                <value>
                    <fullName>Evening</fullName>
                </value>
                <value>
                    <fullName>Night</fullName>
                </value>
                <value>
                    <fullName>Anytime</fullName>
                    <default>true</default>
                    <label>Anytime</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/SyncProductsBatchTest.cls
@IsTest
private class SyncProductsBatchTest {

    @TestSetup
    static void setup() {
        maica_cc__Setting__c setting = new maica_cc__Setting__c();
        setting.maica_cc__API_Name__c = MaicaSetting.SYNC_SETTING;
        setting.Sync_Direction__c = 'Maica to Standard';
        setting.Sync_Mode__c = 'Scheduled';
        upsert setting;

        maica_cc__Support_Category__c supportCategory = new maica_cc__Support_Category__c(
                Name = 'Test Support Category'
        );
        insert supportCategory;

        maica_cc__Support_Item__c supportItemVar = new maica_cc__Support_Item__c(
                Name = 'Test Product',
                maica_cc__Support_Category__c = supportCategory.Id,
                maica_cc__Service_Day__c = 'Anytime',
                maica_cc__Service_Time__c = 'Anytime',
                maica_cc__Quantity_Unit_Of_Measure__c = 'Each',
                maica_cc__Active__c = true
        );
        insert supportItemVar;
    }

    @IsTest
    static void testInsertBehaviour() {
        Response resp = new SyncProductsBatch().process(new Request());
        Assert.isTrue(resp.isValid);

        Test.startTest();
        String jobId = ScheduleManager.schedule(
                ScheduleManager.SYNC_ALL_OBJECTS_JOB_NAME,
                Time.newInstance(4, 0, 0, 0),
                new SyncProductsBatch()
        );
        CronTrigger ct = (CronTrigger) Utils.arrays.firstOrNull([
                SELECT Id
                FROM CronTrigger
                WHERE Id = :jobId
        ]);
        Assert.isNotNull(ct);
        Database.executeBatch(new SyncProductsBatch(true), 100);
        Test.stopTest();

        maica_cc__Support_Item__c supportItemVar = (maica_cc__Support_Item__c) Utils.arrays.firstOrException([
                SELECT Id, Product__c, maica_cc__Support_Category__c, maica_cc__Service_Day__c,
                        maica_cc__Service_Time__c, maica_cc__Quantity_Unit_Of_Measure__c, maica_cc__Active__c
                FROM maica_cc__Support_Item__c
        ], 'No maica_cc__Support_Item__c.');

        List<Product2> products = [
                SELECT Id, Support_Item__c
                FROM Product2
                WHERE Support_Item__c = :supportItemVar.Id
        ];

        Product2 product2Var = (Product2) Utils.arrays.firstOrNull([
                SELECT Id, Support_Item__c, Support_Category__c, Service_Day__c, Service_Time__c,
                        QuantityUnitOfMeasure, IsActive
                FROM Product2
                WHERE Id IN (SELECT Product__c FROM maica_cc__Support_Item__c WHERE Id = :supportItemVar.Id)
                AND Support_Item__c = :supportItemVar.Id
        ]);

        Assert.isTrue(products.size() == 1);
        Assert.isTrue(product2Var != null);
        Assert.isTrue(supportItemVar.Id.equals(product2Var.Support_Item__c));
        Assert.isTrue(product2Var.Id.equals(supportItemVar.Product__c));
        Assert.isTrue(product2Var.IsActive == true && supportItemVar.maica_cc__Active__c.equals(product2Var.IsActive));
        Assert.isTrue(supportItemVar.maica_cc__Quantity_Unit_Of_Measure__c.equals(product2Var.QuantityUnitOfMeasure));
        Assert.isTrue(supportItemVar.maica_cc__Service_Day__c.equals(product2Var.Service_Day__c));
        Assert.isTrue(supportItemVar.maica_cc__Service_Time__c.equals(product2Var.Service_Time__c));
        Assert.isTrue(supportItemVar.maica_cc__Support_Category__c.equals(product2Var.Support_Category__c));
    }

    @IsTest
    static void testUpdateBehaviour() {
        maica_cc__Support_Item__c supportItemVar = (maica_cc__Support_Item__c) Utils.arrays.firstOrException([
                SELECT Id, Product__c, maica_cc__Support_Category__c, maica_cc__Service_Day__c,
                        maica_cc__Service_Time__c, maica_cc__Quantity_Unit_Of_Measure__c, maica_cc__Active__c
                FROM maica_cc__Support_Item__c
        ], 'No maica_cc__Support_Item__c.');
        supportItemVar.maica_cc__Service_Time__c = 'Daytime';
        update supportItemVar;

        Test.startTest();
        Database.executeBatch(new SyncProductsBatch(), 100);
        Test.stopTest();

        Product2 product2Var = (Product2) Utils.arrays.firstOrNull([
                SELECT Id, Service_Time__c
                FROM Product2
                WHERE Id IN (SELECT Product__c FROM maica_cc__Support_Item__c WHERE Id = :supportItemVar.Id)
                AND Support_Item__c = :supportItemVar.Id
        ]);

        Assert.isTrue('Daytime'.equals(supportItemVar.maica_cc__Service_Time__c) && supportItemVar.maica_cc__Service_Time__c.equals(product2Var.Service_Time__c));
    }

    @IsTest
    static void testDelete() {
        maica_cc__Support_Item__c supportItemVar = (maica_cc__Support_Item__c) Utils.arrays.firstOrException([
                SELECT Id, Product__c, maica_cc__Support_Category__c, maica_cc__Service_Day__c,
                        maica_cc__Service_Time__c, maica_cc__Quantity_Unit_Of_Measure__c, maica_cc__Active__c
                FROM maica_cc__Support_Item__c
        ], 'No maica_cc__Support_Item__c.');
        delete supportItemVar;

        Test.startTest();
        Database.executeBatch(new SyncProductsBatch(), 100);
        Test.stopTest();

        Product2 product2Var = (Product2) Utils.arrays.firstOrNull([
                SELECT Id
                FROM Product2
                WHERE Id IN (SELECT Product__c FROM maica_cc__Support_Item__c WHERE Id = :supportItemVar.Id)
                AND Support_Item__c = :supportItemVar.Id
        ]);
        Assert.isNull(product2Var);
    }

    @IsTest
    static void testCatch() {
        SyncProductsBatch bc = new SyncProductsBatch();
        bc.execute(null, null);
        maica_cc__Log__c log = (maica_cc__Log__c) Utils.arrays.firstOrNull([
                SELECT Id, maica_cc__Details__c
                FROM maica_cc__Log__c
        ]);
        Assert.isNotNull(log);
        Assert.areEqual('Attempt to de-reference a null object', log.maica_cc__Details__c, 'Error message should be \'Attempt to de-reference a null object\'');
    }
}