src/objects/maica_cc__Price_List__c.object
<CustomObject>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Price Lists</relationshipLabel>
        <relationshipName>Price_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/maica_cc__Price_List_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Price_Book_Entry__c</fullName>
        <label>Price Book Entry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/maica_cc__Setting__c.object
<CustomObject>
    <fields>
        <fullName>Sync_Direction__c</fullName>
        <description>Setting API Name:Sync_Setting</description>
        <label>Sync Direction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Maica to Standard</fullName>
                </value>
                <value>
                    <fullName>Standard to Maica</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sync_Mode__c</fullName>
        <defaultValue>&apos;Triggered&apos;</defaultValue>
        <description>Setting API Name:Sync_Setting</description>
        <label>Sync Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Triggered</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>On Demand</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/maica_cc__Support_Item__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Support Items</relationshipLabel>
        <relationshipName>Support_Items</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Price_List_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price List Entry</label>
        <referenceTo>maica_cc__Price_List_Entry__c</referenceTo>
        <relationshipLabel>Price Book Entries</relationshipLabel>
        <relationshipName>Price_Book_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Support_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Support Item</label>
        <referenceTo>maica_cc__Support_Item__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Support_Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Represents the Support Category that the Product belongs to.</description>
        <inlineHelpText>Represents the Support Category that the Product belongs to.</inlineHelpText>
        <label>Support Category</label>
        <referenceTo>maica_cc__Support_Category__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Day__c</fullName>
        <description>The specific day or delivery window when the Product is eligible for Service Delivery.</description>
        <inlineHelpText>The specific day or delivery window when the Product is eligible for Service Delivery.</inlineHelpText>
        <label>Service Day</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Weekday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Public Holiday</fullName>
                </value>
                <value>
                    <fullName>Anytime</fullName>
                    <default>true</default>
                    <label>Anytime</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Time__c</fullName>
        <description>The specific time of day when the Product is eligible for Service Delivery.</description>
        <inlineHelpText>The specific time of day when the Product is eligible for Service Delivery.</inlineHelpText>
        <label>Service Time</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daytime</fullName>
                </value>
                <value>
                    <fullName>Afternoon</fullName>
                </value>
                <value>
                    <fullName>Evening</fullName>
                </value>
                <value>
                    <fullName>Night</fullName>
                </value>
                <value>
                    <fullName>Anytime</fullName>
                    <default>true</default>
                    <label>Anytime</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/SyncPriceListEntriesBatchTest.cls
@IsTest
private class SyncPriceListEntriesBatchTest {

    @TestSetup
    static void setup() {
        maica_cc__Setting__c setting = new maica_cc__Setting__c();
        setting.maica_cc__API_Name__c = MaicaSetting.SYNC_SETTING;
        setting.Sync_Direction__c = 'Standard to Maica';
        setting.Sync_Mode__c = 'Scheduled';
        upsert setting;

        maica_cc__Support_Category__c supportCategory = new maica_cc__Support_Category__c(
                Name = 'Test Support Category'
        );
        insert supportCategory;

        Product2 product2Var = new Product2(
                Name = 'Test Product',
                Support_Category__c = supportCategory.Id,
                Service_Day__c = 'Anytime',
                Service_Time__c = 'Anytime'
        );
        insert product2Var;

        new SyncSupportItemsBatch().execute(null, new List<SObject>{
                product2Var
        });

        List<maica_cc__Support_Item__c> supportItems = [
                SELECT Id, Product__c
                FROM maica_cc__Support_Item__c
                WHERE Product__c = :product2Var.Id
        ];
        Assert.isTrue(!supportItems.isEmpty());
        Assert.isTrue(supportItems.size() == 1);

        Pricebook2 pbVar = new Pricebook2(
                Name = 'Test Price List'
        );
        insert pbVar;

        new SyncPriceListsBatch().execute(null, new List<SObject>{
                pbVar
        });

        List<maica_cc__Price_List__c> priceLists = [
                SELECT Id, Price_Book__c
                FROM maica_cc__Price_List__c
                WHERE Price_Book__c = :pbVar.Id
        ];
        Assert.isTrue(!priceLists.isEmpty());
        Assert.isTrue(priceLists.size() == 1);

        PricebookEntry standardPbeVar = new PricebookEntry(
                Product2Id = product2Var.Id,
                Pricebook2Id = Test.getStandardPricebookId(),
                IsActive = true,
                UnitPrice = 10
        );
        insert standardPbeVar;

        PricebookEntry pbeVar = new PricebookEntry(
                Product2Id = product2Var.Id,
                Pricebook2Id = pbVar.Id,
                IsActive = true,
                UnitPrice = 10
        );
        insert pbeVar;
    }

    @IsTest
    static void testInsertBehaviour() {
        Response resp = new SyncPriceListEntriesBatch().process(new Request());
        Assert.isTrue(resp.isValid);

        Test.startTest();
        Database.executeBatch(new SyncPriceListEntriesBatch(), 100);
        Test.stopTest();

        PricebookEntry pbeVar = (PricebookEntry) Utils.arrays.firstOrException([
                SELECT Id, Price_List_Entry__c, Product2Id, IsActive,
                        UnitPrice, Product2.Support_Item__c, Pricebook2.Price_List__c
                FROM PricebookEntry
                WHERE Pricebook2Id != :Test.getStandardPricebookId()
        ], 'No PricebookEntry.');

        maica_cc__Price_List_Entry__c pleVar = (maica_cc__Price_List_Entry__c) Utils.arrays.firstOrNull([
                SELECT Id, maica_cc__Unit_Price__c, maica_cc__Active__c, maica_cc__Support_Item__c, maica_cc__Price_List__c, Price_Book_Entry__c
                FROM maica_cc__Price_List_Entry__c
                WHERE Price_Book_Entry__c = :pbeVar.Id
        ]);

        List<maica_cc__Price_List_Entry__c> entries = [
                SELECT Id, Price_Book_Entry__c
                FROM maica_cc__Price_List_Entry__c
        ];
        Assert.isTrue(!entries.isEmpty());
        Assert.isTrue(entries.size() == 1);
        Assert.isTrue(pleVar != null);
        Assert.isTrue(pbeVar.Id.equals(pleVar.Price_Book_Entry__c));
        Assert.isTrue(pleVar.Id.equals(pbeVar.Price_List_Entry__c));
        Assert.isTrue(pleVar.maica_cc__Active__c == true && pbeVar.IsActive.equals(pleVar.maica_cc__Active__c));
        Assert.isTrue(pleVar.maica_cc__Unit_Price__c == pbeVar.UnitPrice);
        Assert.isTrue(pleVar.maica_cc__Support_Item__c.equals(pbeVar.Product2?.Support_Item__c));
        Assert.isTrue(pleVar.maica_cc__Price_List__c.equals(pbeVar.Pricebook2?.Price_List__c));
    }

    @IsTest
    static void testUpdateBehaviour() {
        PricebookEntry pbeVar = (PricebookEntry) Utils.arrays.firstOrException([
                SELECT Id, Price_List_Entry__c, Product2Id, IsActive,
                        UnitPrice, Product2.Support_Item__c, Pricebook2.Price_List__c
                FROM PricebookEntry
                WHERE Pricebook2Id != :Test.getStandardPricebookId()
        ], 'No PricebookEntry.');
        pbeVar.UnitPrice = 12;
        update pbeVar;

        Test.startTest();
        Database.executeBatch(new SyncPriceListEntriesBatch(), 100);
        Test.stopTest();

        maica_cc__Price_List_Entry__c pleVar = (maica_cc__Price_List_Entry__c) Utils.arrays.firstOrNull([
                SELECT Id, maica_cc__Unit_Price__c
                FROM maica_cc__Price_List_Entry__c
                WHERE Price_Book_Entry__c = :pbeVar.Id
        ]);
        List<PricebookEntry> entries = [
                SELECT Id
                FROM PricebookEntry
                WHERE Pricebook2Id != :Test.getStandardPricebookId()
        ];

        Assert.isTrue(pbeVar != null);
        Assert.isTrue(!entries.isEmpty());
        Assert.isTrue(entries.size() == 1);
        Assert.isTrue(pleVar.maica_cc__Unit_Price__c == pbeVar.UnitPrice);
    }

    @IsTest
    static void testDelete() {
        PricebookEntry pbeVar = (PricebookEntry) Utils.arrays.firstOrException([
                SELECT Id, Price_List_Entry__c, Product2Id, IsActive,
                        UnitPrice, Product2.Support_Item__c, Pricebook2.Price_List__c
                FROM PricebookEntry
                WHERE Pricebook2Id != :Test.getStandardPricebookId()
        ], 'No PricebookEntry.');
        delete pbeVar;

        Test.startTest();
        Database.executeBatch(new SyncPriceListEntriesBatch(), 100);
        Test.stopTest();

        maica_cc__Price_List_Entry__c pleVar = (maica_cc__Price_List_Entry__c) Utils.arrays.firstOrNull([
                SELECT Id, maica_cc__Unit_Price__c
                FROM maica_cc__Price_List_Entry__c
                WHERE Price_Book_Entry__c = :pbeVar.Id
        ]);
        Assert.isNull(pleVar);
    }

    @IsTest
    static void testCatch() {
        SyncPriceListEntriesBatch bc = new SyncPriceListEntriesBatch();
        bc.execute(null, null);
        maica_cc__Log__c log = (maica_cc__Log__c) Utils.arrays.firstOrNull([
                SELECT Id, maica_cc__Details__c
                FROM maica_cc__Log__c
        ]);
        Assert.isNotNull(log);
        Assert.areEqual('Attempt to de-reference a null object', log.maica_cc__Details__c, 'Error message should be \'Attempt to de-reference a null object\'');
    }
}