src/objects/maica_cc__Setting__c.object
<CustomObject>
    <fields>
        <fullName>Sync_Direction__c</fullName>
        <description>Setting API Name:Sync_Setting</description>
        <label>Sync Direction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Maica to Standard</fullName>
                </value>
                <value>
                    <fullName>Standard to Maica</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sync_Mode__c</fullName>
        <defaultValue>&apos;Triggered&apos;</defaultValue>
        <description>Setting API Name:Sync_Setting</description>
        <label>Sync Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Triggered</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>On Demand</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/SettingsSyncMetaProc.cls
public without sharing class SettingsSyncMetaProc extends MetadataProcessor {

    public override Response process(Request request) {
        this.request = request == null ? new MetadataProcessor.MetadataRequest() : (MetadataProcessor.MetadataRequest) request;

        this.request.fields = new Set<SObjectField>{
                maica_cc__Setting__c.Sync_Mode__c,
                maica_cc__Setting__c.Sync_Direction__c
        };

        super.process(this.request);

        this.init();

        return this.response;
    }

    private void init() {
        maica_cc__Setting__c setting = MaicaSetting.sync;
        this.response.getMapper().mapFromSObject('setting', setting);

        CronTrigger syncCronTrigger = ScheduleManager.getScheduled(ScheduleManager.SYNC_ALL_OBJECTS_JOB_NAME);
        Time syncTime = syncCronTrigger?.NextFireTime?.time();
        if (syncTime == null) {
            syncTime = Time.newInstance(4, 0, 0, 0);
        }
        this.response.put('syncTime', syncTime);

        CronTrigger entriesSyncCronTrigger = ScheduleManager.getScheduled(ScheduleManager.SYNC_PRICE_LIST_ENTRIES_SCHEDULED_JOB_NAME);
        Time entriesSyncTime = entriesSyncCronTrigger?.NextFireTime ?.time();
        if (entriesSyncTime == null) {
            entriesSyncTime = Time.newInstance(4, 0, 0, 0);
        }
        this.response.put('entriesSyncTime', entriesSyncTime);
    }
}