src/objects/maica_cc__Setting__c.object
<CustomObject>
    <fields>
        <fullName>Sync_Direction__c</fullName>
        <description>Setting API Name:Sync_Setting</description>
        <label>Sync Direction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Maica to Standard</fullName>
                </value>
                <value>
                    <fullName>Standard to Maica</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sync_Mode__c</fullName>
        <defaultValue>&apos;Triggered&apos;</defaultValue>
        <description>Setting API Name:Sync_Setting</description>
        <label>Sync Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Triggered</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>On Demand</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/SettingsSyncTest.cls
@IsTest
private class SettingsSyncTest {

    @IsTest
    static void testMetaProc() {
        Response resp = new SettingsSyncMetaProc().process(new MetadataProcessor.MetadataRequest());
        Assert.isTrue(resp.isValid);
        Assert.areEqual(resp.getTime('syncTime'), Time.newInstance(4, 0, 0, 0), 'Sync time should be 4:00:00');
        Assert.areEqual(resp.getTime('entriesSyncTime'), Time.newInstance(4, 0, 0, 0), 'Sync time should be 4:00:00');
    }

    @IsTest
    static void testSubmitProc() {
        MaicaSetting.CACHING = false;
        maica_cc__Setting__c setting = new maica_cc__Setting__c();
        setting.maica_cc__API_Name__c = MaicaSetting.SYNC_SETTING;
        setting.Sync_Direction__c = 'Standard to Maica';
        setting.Sync_Mode__c = 'Scheduled';
        upsert setting;

        Test.startTest();
        Response resp = new SettingsSyncSubmitProc().process(new Map<String, Object>{
                'setting' =>  new AutoMapper().getSObjectAsMap(setting)

        });
        CronTrigger ct = (CronTrigger) Utils.arrays.firstOrNull([
                SELECT Id
                FROM CronTrigger
                WHERE CronJobDetail.Name = :ScheduleManager.SYNC_ALL_OBJECTS_JOB_NAME
        ]);
        Assert.isNotNull(ct);
        Test.stopTest();

        setting.Sync_Mode__c = 'Triggered';
        upsert setting;

        resp = new SettingsSyncSubmitProc().process(new Map<String, Object>{
                'setting' =>  new AutoMapper().getSObjectAsMap(setting)
        });
        ct = (CronTrigger) Utils.arrays.firstOrNull([
                SELECT Id
                FROM CronTrigger
                WHERE CronJobDetail.Name = :ScheduleManager.SYNC_ALL_OBJECTS_JOB_NAME
        ]);
        Assert.isNull(ct);
        Assert.isTrue(resp.isValid);
    }
}